# Generated by Django 5.2.15 on 2026-06-16 06:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Kindly enter a valid phone number.', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
